{"trial_id": "00", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "num_neurons_main", "default": null, "conditions": [], "min_value": 10, "max_value": 100, "step": 15, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_layers_main", "default": null, "conditions": [], "min_value": 2, "max_value": 5, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_neurons_int", "default": null, "conditions": [], "min_value": 20, "max_value": 100, "step": 20, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_layers_int", "default": null, "conditions": [], "min_value": 2, "max_value": 10, "step": 2, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_rate", "default": 0.0, "conditions": [], "min_value": 0.0, "max_value": 0.3, "step": 0.1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_keypoints", "default": null, "conditions": [], "min_value": 10, "max_value": 40, "step": 10, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_vertices", "default": null, "conditions": [], "min_value": 2, "max_value": 10, "step": 2, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "lambd_mc", "default": 0.001, "conditions": [], "min_value": 0.001, "max_value": 1.0, "step": null, "sampling": "log"}}, {"class_name": "Float", "config": {"name": "lambd_smoothness", "default": 1e-05, "conditions": [], "min_value": 1e-05, "max_value": 0.01, "step": null, "sampling": "log"}}, {"class_name": "Float", "config": {"name": "learning_rate", "default": 0.0001, "conditions": [], "min_value": 0.0001, "max_value": 0.01, "step": null, "sampling": "log"}}], "values": {"num_neurons_main": 55, "num_layers_main": 4, "num_neurons_int": 20, "num_layers_int": 2, "dropout_rate": 0.1, "num_keypoints": 30, "num_vertices": 4, "lambd_mc": 0.09824711447422325, "lambd_smoothness": 0.003042866783260263, "learning_rate": 0.0006623877270603919}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/eager/execute.py\", line 59, in quick_execute\n    except TypeError as e:\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node model/X4_calibrator_pairwise_X4_X3/concat defined at (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n\n  File \"<frozen runpy>\", line 88, in _run_code\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/asyncio/base_events.py\", line 608, in run_forever\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/asyncio/base_events.py\", line 1936, in _run_once\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/asyncio/events.py\", line 84, in _run\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n\n  File \"/var/folders/30/wpb2n_hs72q5fz9yvp8c1cth0000gv/T/ipykernel_97979/1118812695.py\", line 15, in <module>\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/engine/training.py\", line 1856, in fit\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/engine/training.py\", line 2296, in evaluate\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/engine/training.py\", line 4108, in run_step\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 832, in __call__\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 888, in _call\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 695, in _initialize\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 178, in trace_function\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 283, in _maybe_define_function\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 310, in _create_concrete_function\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/framework/func_graph.py\", line 1059, in func_graph_from_py_func\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 598, in wrapped_fn\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/autograph_util.py\", line 41, in autograph_handler\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/engine/training.py\", line 2066, in test_function\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/engine/training.py\", line 2049, in step_function\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 1681, in run\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 3271, in call_for_each_replica\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 4069, in _call_for_each_replica\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/engine/training.py\", line 2037, in run_step\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/engine/training.py\", line 1917, in test_step\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/engine/training.py\", line 590, in __call__\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/engine/base_layer.py\", line 1149, in __call__\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/engine/functional.py\", line 515, in call\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/engine/functional.py\", line 672, in _run_internal_graph\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/engine/base_layer.py\", line 1149, in __call__\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow_lattice/python/pwl_calibration_layer.py\", line 460, in call\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow_lattice/python/pwl_calibration_lib.py\", line 118, in compute_interpolation_weights\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/autograph/operators/control_flow.py\", line 1217, in if_stmt\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/autograph/operators/control_flow.py\", line 1270, in _py_if_stmt\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow_lattice/python/pwl_calibration_lib.py\", line 119, in compute_interpolation_weights\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/util/dispatch.py\", line 1260, in op_dispatch_handler\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/ops/array_ops.py\", line 1688, in concat\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/ops/gen_array_ops.py\", line 1316, in concat_v2\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/framework/op_def_library.py\", line 796, in _apply_op_helper\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/framework/func_graph.py\", line 670, in _create_op_internal\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/framework/ops.py\", line 2652, in _create_op_internal\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/framework/ops.py\", line 1160, in from_node_def\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/framework/ops.py\", line 1026, in _create_c_op\n\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/util/tf_stack.py\", line 162, in extract_stack\n\nConcatOp : Ranks of all input tensors should match: shape[0] = [0] vs. shape[1] = [1000,29]\n\t [[{{node model/X4_calibrator_pairwise_X4_X3/concat}}]] [Op:__inference_test_function_11910072]\n"}